### PR TITLE
Support JSON/JSONB types for queries and mutations

### LINKED ISSUE #105: Support JSON and JSONB types as escaped strings
Currently, json/b columns are excluded from the schema

Enable them, and treat them as escaped strings

### PR DESCRIPTION
**Pull request by olirice**
## What kind of change does this PR introduce?
Adds support for JSON and JSONB types in queries and mutations

Note:
JSON/B fields continue to be unavailable as targets for filtering or sorting because it isn't clear which operations should be supported, or how they should behave

resolves #105

### CODE REVIEW

**Comment by olirice** [comment]
Note:

This upgrades libgraphqlparser from 0.7.0 to current HEAD to get the bugfix https://github.com/graphql/libgraphqlparser/commit/534a3cffd19a3c452b981fc9e12e66c5303c2033

there is an open issue from 2020 asking for a new release https://github.com/graphql/libgraphqlparser/issues/101 but no one has responded

libgraphqlparser will need to be updated on the supabase platform before this can go out

**Review by burggraf — APPROVED** [review]

**Comment by rhacker** [comment]
this is cool. when do we expect this feature to be rolled out on the supabase platform?

**Comment by olirice** [comment]
@rhacker this was included in release `0.3.2` and is available on new projects already. There is a delay getting it rolled out to existing projects because a couple of updates have to happen in sequence (libgraphqlparser) but that should be resolved within 10 days or so

You can check the version installed with
```sql
select * from pg_available_extensions where name = 'pg_graphql'
```

and if you need the feature urgently I can have an existing project upgraded for you if you send me the project_ref

**Comment by olirice** [comment]
@rhacker its rolling out this weekend

**Pull request merged**
