### PR TITLE
String regex filters

### PR DESCRIPTION
**Pull request by robertn702**
## What kind of change does this PR introduce?
- Feature
- Docs update

## What is the current behavior?
The current behavior lacks the ability to filter text columns by regular expressions.

## What is the new behavior?
The following string filters have been added:
- `regex`: Case sensitive regex match
- `iregex`: Case insensitive regex match
- `nregex`: Case sensitive negative regex match
- `niregex`: Case insensitive negative regex match

These have been implemented using [Postgres RegEx operators](https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-POSIX-REGEXP)
- `~`
- `~*`
- `!~`
- `!~*`

## Additional context
Proposal: [RegEx matching filter](https://github.com/supabase/pg_graphql/issues/350)

### CODE REVIEW

**Comment by robertn702** [comment]
@olirice I went with Hasura's naming convention — `regex` instead of `match`. I can switch it out if you prefer a different naming convention.

Also, wasn't sure what the guidelines were for the tests. When running the tests the following fail: `resolve_graphiql_schema`, `string_filters`.

The `regressions.diff` shows the expected output for `string_filters`, but not sure if I'm supposed to copy the diff to `string_filters.out` or not.

I couldn't find any output about the `resolve_graphiql_schema` failure.

**Comment by olirice** [comment]
> regex instead of match. I can switch it out if you prefer a different naming convention.

I'll check PostgREST, Hasura, and a few others to see if there's a consensus but `regex` sounds good to me

> The regressions.diff shows the expected output for string_filters, but not sure if I'm supposed to copy the diff to string_filters.out or not

yes, the workflow is to update the tests, run them, and then copy the new `.out` file into `tests/expected` after manually confirming that its what you expect

--

great work, I'll do a proper review tomorrow

I'm not totally sold on `nregex` and `niregex`. are you aware of an example where `nregex` than a negation with `regex`?

**Comment by robertn702** [comment]
> I'm not totally sold on nregex and niregex. are you aware of an example where nregex than a negation with regex?

I think the main reason for a separate operator is that Postgres uses POSIX RegEx which doesn't include lookarounds (the usual negation method). This makes negative lookups difficult, or not possible — I'm not sure. The `nregex` and `niregex` makes negation trivial. For example, if I want to exclude any strings that contain curse words:

```json
{
  "text": {
    "niregex": "(curse1|curse2|curse3)"
  }
}
```

I tried to research how I would do this with the `regex` operator but still not sure how it would be done.

**Comment by olirice** [comment]
We discussed this internally today and decided that it would make for a more consistent API if negated regexes used the same `and`, `or`, `not` system described in issue https://github.com/supabase/pg_graphql/issues/87 rather than dedicated operators

the `not` feature doesn't exist yet, so you'll be stuck with negating inside the regex in the short term, but mid-term I think that'll make for the best API

thanks again for your work on this!

**Pull request merged**
