### PR TITLE
add support for array arguments and return types in UDFs

### PR DESCRIPTION
**Pull request by imor**
## What kind of change does this PR introduce?

Feature

## What is the current behavior?

Arrays are not supported in arguments and as return types of user defined functions.

## What is the new behavior?

Arrays are supported in arguments and as return types of user defined functions.

## Additional context

Default values for array type arguments are not supported.

### CODE REVIEW

**Comment by imor** [comment]
@olirice arrays of composite types are filtered out now. Docs and changelog have also been updated.

**Review by olirice — APPROVED** [review]
I just noticed the logic for applying [enum variant remapping](https://supabase.github.io/pg_graphql/configuration/#enum-variant) is in `ColumnBuilder` so those re-mapping will not take effect if a function returns a scalar enum or an array of enum.

I've approved, but please either:
- filter those function types out
- refactor the logic so it applies to function returns too

everything else you've got here looks great!

**Comment by imor** [comment]
Filtered out functions with enum and enum arrays as args or return values. Added a task in #410 to add support for them.

**Comment by dvv** [comment]
@imor Please verify this is not my setup and help to get rid of errors:

```sql
begin;

create schema if not exists a1; grant usage on schema a1 to public;
create table a1.foo(id int primary key); grant select on table a1.foo to public;
insert into a1.foo (id) values (1);
create or replace function a1.bar(a1.foo) returns int[] stable return array[1, 2, 3]::int[];
grant execute on function a1.bar(a1.foo) to public;
create or replace function a1._the_foo(a1.foo) returns int[] stable return array[1, 2, 3]::int[];
grant execute on function a1._the_foo(a1.foo) to public;
set local search_path to a1;
comment on schema a1 is e'@graphql({"inflect_names": true})';
select graphql.resolve($$query {fooCollection {edges{node{ id bar }}}}$$); -- invalid return type from function
select graphql.resolve($$query {fooCollection {edges{node{ id the_foo }}}}$$); -- Unknown field 'the_foo' on type 'Foo'
select graphql.resolve($$query {fooCollection {edges{node{ id _the_foo }}}}$$); -- Unknown field '_the_foo' on type 'Foo'

rollback;
```

**Pull request merged**
