### PR TITLE
Max rows configurable by comment directive on schema

### LINKED ISSUE #257: why limit records under 30?
Hi,

When querying with the `first` attribute, it always returns 30 records maximum. May I know the reason? After searching Google, documentation, and repo issues, no useful information was found.

1. https://github.com/supabase/pg_graphql/blob/master/src/transpile.rs#L757
2. https://github.com/supabase/pg_graphql/blob/master/test/expected/max_page_size.out#L7

### PR DESCRIPTION
**Pull request by olirice**
Adds a comment directive
```sql
comment on schema public is e'@graphql({"max_rows": 100})';
```
to adjust the number of rows returned on each page of a collection from the default of 30

resolves #257

### CODE REVIEW

**Review by alaister — APPROVED** [review]

**Comment by unknown1337** [comment]
(I think the documentation on this is missing? ;) )

**Comment by unknown1337** [comment]
Thanks for implementing! could it be correct that support for this (max rows directive) is not yet released at supabase (02-02-2023)? Thanks!

**Comment by olirice** [comment]
@unknown1337 the latest release of pg_graphql `v1.1.0` is available on supabase for new projects. Existing projects typically receive updates 1-3 weeks later. I just pinged asking for `v1.1.0` to push out to existing projects.

Once that happens, running the following query
```sql
select * from pg_available_extensions where name = 'pg_graphql'
``` 
will show `default_version` as = `1.1.0`

---

If you don't see `1.1.0` available by Tuesday, shoot me an email (from GH profile) with your project ref and I'll make sure it get updated off-cycle

**Comment by unknown1337** [comment]
Great, thanks!

**Comment by olirice** [comment]
@unknown1337 it rolled out this morning, you should be good to go now

**Comment by lopezjurip** [comment]
Any way to change this only on a specific table?

**Comment by olirice** [comment]
the comment directive only applies at the schema level. If you want to override that for a particular table/query the best bet would be to use the "first" argument in the query

**Comment by lopezjurip** [comment]
That would be the case if i want less rows. But in my use case I want to limit every table to 100 but increase the limit to 500 for a specific table.

**Comment by olirice** [comment]
got it, unfortunately we don't currently support that pattern
you're welcome to open a dedicated issue for it

**Pull request merged**
