### PR TITLE
Bump version numbers for 1.5.6

### PR DESCRIPTION
**Pull request by olirice**
## What kind of change does this PR introduce?
Release version 1.5.6

### CODE REVIEW

**Comment by leefordjudes** [comment]
Kindly review it as earliest as possible. and release this version. I need an array filter.

**Comment by esakkimuthu-p** [comment]
Kindly release this version as soon as possible.

**Review by imor — APPROVED** [review]

**Comment by olirice** [comment]
@esakkimuthu-p the release has been tagged and the assets are now building

**Comment by morasaek** [comment]
@olirice Thanks for releasing these changes! Are you able to help get another PR created for this version in the supabase repo? I noticed that you put up the PR in the past (https://github.com/supabase/postgres/pull/967), so I thought I'd ask haha

**Comment by olirice** [comment]
sure, tracking here https://github.com/supabase/postgres/pull/1008

**Pull request merged**
