### PR TITLE
String Filter Ops

### LINKED ISSUE #193: `LIKE`/`ILIKE`/`NOT LIKE` operator support for filter types
## Summary
Add support for `like`/`ilike`/`not like`/`not ilike` filtering to get a collection of records that matches the given filter string.

E.g. `filter: { label: { like: "Egg%" } }`

## Rationale
Filtering on string partials is a common use case for us.

### PR DESCRIPTION
**Pull request by olirice**
## What kind of change does this PR introduce?

Add filter types for String types:
- [x] `startsWith`
- [x] make sure that `startsWith` ignores wildcards and uses indexes when available
- [x] `like`
- [x] `ilike`

Blockers:
- [x] (separate PR) unknown types are currently represented as `String`. That was fine when `String` supported few filter ops but it no longer make sense if we're adding `like` etc. Need to create a new `Opaque` type to use for exotic pg types like `inet`, or types provided by extensions so we don't give `like` filtering to all the random stuff in addition to text/varchar pg_types. Tracking in #316 
- [x] (separate PR) update `Scalar::String` to `Scalar::String(Option<i32>)` to handle type mods on varchar(n) and char(n) types so they can be validated during parsing. related #192 

Future:
At some point we're likely to need to be able to restrict  the filter operations per-column

---
resolves #193

### CODE REVIEW

**Review by alaister — APPROVED** [review]

**Comment by rlee1990** [comment]
Is this available to be used if we are using the hosted version of Supabase?

**Comment by olirice** [comment]
@rlee1990 still needs to be merged into supabase/postgres and (separate) rolled out for existing projects. That'll happen over the next week or two

But if you need it now, please send me your project ref and I can get it updated manually

**Comment by rlee1990** [comment]
@olirice here is the project ref ID: tqrwgrwawwsfzpqlzswj

**Comment by olirice** [comment]
@rlee1990 v1.2.0 is now available on your project. To enable it run
```sql
drop extension pg_graphql;
create extension pg_graphql;
```

**Comment by rlee1990** [comment]
> 

Thanks will do

**Comment by robertn702** [comment]
> But if you need it now, please send me your project ref and I can get it updated manually

@olirice dmed you in Discord with project id

**Comment by olirice** [comment]
thanks! all set. more info in the discord chat

**Pull request merged**
